"""Regenerate data/mo-boosts-40.xml (and the 10/20/30 override sets) from mo-deeds-gameeffects.xml.

Every ENI_MO_BOOST_* copies the SubjectRequirements of its ENI_MO_MARK_* twin verbatim, so a
deed's requirement can never drift between the marker (which drives the UI) and the boost
(which pays the research). Edit the deeds file only, then run this.

Same shape as tools/gen-eni-ex-boosts.py. The 10/20/30 sets are <Update> patches against the
ModifierArguments rows the 40 percent base file creates, so the base ActionGroup MUST be declared
before the override groups in the modinfo - see the load-order comment there.
"""
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'mods', 'eureka-inspiration', 'data')

# Deed key -> (node id, progression system). ABSOLUTISM is the display name Chris chose for the
# node the data calls NODE_CIVIC_MO_BRANCH_AUTHORITARIANISM.
NODES = {
    'ELECTRICITY': ('NODE_TECH_MO_ELECTRICITY', 'SYSTEM_TECH'),
    'URBANIZATION': ('NODE_TECH_MO_URBANIZATION', 'SYSTEM_TECH'),
    'COMBUSTION': ('NODE_TECH_MO_COMBUSTION', 'SYSTEM_TECH'),
    'INDUSTRIALIZATION': ('NODE_TECH_MO_INDUSTRIALIZATION', 'SYSTEM_TECH'),
    'RADIO': ('NODE_TECH_MO_RADIO', 'SYSTEM_TECH'),
    'FLIGHT': ('NODE_TECH_MO_FLIGHT', 'SYSTEM_TECH'),
    'MASS_PRODUCTION': ('NODE_TECH_MO_MASS_PRODUCTION', 'SYSTEM_TECH'),
    'COMPUTATION': ('NODE_TECH_MO_COMPUTATION', 'SYSTEM_TECH'),
    'MOBILIZATION': ('NODE_TECH_MO_MOBILIZATION', 'SYSTEM_TECH'),
    'ARMOR': ('NODE_TECH_MO_ARMOR', 'SYSTEM_TECH'),
    'AERODYNAMICS': ('NODE_TECH_MO_AERODYNAMICS', 'SYSTEM_TECH'),
    'NUCLEAR_FISSION': ('NODE_TECH_MO_NUCLEAR_FISSION', 'SYSTEM_TECH'),
    'ROCKETRY': ('NODE_TECH_MO_ROCKETRY', 'SYSTEM_TECH'),
    # POLITICAL_THEORY is NOT listed here. It is one marker per civ-unique civics tree, written by
    # tools/gen-eni-mo-political-theory.py, so the keys change whenever a civ DLC ships. They are
    # discovered from the deeds file below instead of being retyped here.
    'GLOBALISM': ('NODE_CIVIC_MO_MAIN_GLOBALISM', 'SYSTEM_CULTURE'),
    'NATIONALISM': ('NODE_CIVIC_MO_MAIN_NATIONALISM', 'SYSTEM_CULTURE'),
    'CAPITALISM': ('NODE_CIVIC_MO_MAIN_CAPITALISM', 'SYSTEM_CULTURE'),
    'MILITARISM': ('NODE_CIVIC_MO_MAIN_MILITARISM', 'SYSTEM_CULTURE'),
    'HEGEMONY': ('NODE_CIVIC_MO_MAIN_HEGEMONY', 'SYSTEM_CULTURE'),
    'LIBERALISM': ('NODE_CIVIC_MO_BRANCH_LIBERALISM', 'SYSTEM_CULTURE'),
    'PROGRESSIVISM': ('NODE_CIVIC_MO_BRANCH_PROGRESSIVISM', 'SYSTEM_CULTURE'),
    'RADICALISM': ('NODE_CIVIC_MO_BRANCH_RADICALISM', 'SYSTEM_CULTURE'),
    'ABSOLUTISM': ('NODE_CIVIC_MO_BRANCH_AUTHORITARIANISM', 'SYSTEM_CULTURE'),
    'CENTRALISM': ('NODE_CIVIC_MO_BRANCH_CENTRALISM', 'SYSTEM_CULTURE'),
    'SOCIALISM': ('NODE_CIVIC_MO_BRANCH_SOCIALISM', 'SYSTEM_CULTURE'),
}

src = open(os.path.join(ROOT, 'mo-deeds-gameeffects.xml'), encoding='utf-8').read()
reqs = dict(re.findall(
    r'<Modifier id="ENI_MO_MARK_([A-Z_]+)"[^>]*>\s*(<SubjectRequirements[^>]*>.*?</SubjectRequirements>)',
    src, re.S))

# Political Theory's markers are generated one per civ-unique civics tree, so their count moves
# with the installed DLC. Sweep them in rather than hard-coding a list that would go stale silently.
for key in reqs:
    if key.startswith('POLITICAL_THEORY_'):
        NODES[key] = ('NODE_CIVIC_MO_MAIN_POLITICAL_THEORY', 'SYSTEM_CULTURE')
if not any(k.startswith('POLITICAL_THEORY_') for k in NODES):
    raise SystemExit('no ENI_MO_MARK_POLITICAL_THEORY_* markers found - run '
                     'tools/gen-eni-mo-political-theory.py first')

# Story-delivered deeds carry NO SubjectRequirements. Their condition lives in a POLLED
# RequirementSet that mo-stories.xml reads, and the marker + boost are attached as story rewards -
# so they get no requirements block, no attach wrapper and no bind row. Absolutism is delivered this
# way because REQUIREMENT_PLAYER_RAZED_X_CITIES is table-form-only in the base game and a litmus
# showed the other requirement of that class is inert inside a live modifier (2026-08-04).
STORY = {'ABSOLUTISM', 'LIBERALISM'}

missing = [k for k in NODES if k not in reqs and k not in STORY]
if missing:
    raise SystemExit('no requirements found for: %s' % ', '.join(missing))
extra = [k for k in reqs if k not in NODES]
if extra:
    raise SystemExit('marker with no NODES entry: %s' % ', '.join(extra))
stray = [k for k in STORY if k in reqs]
if stray:
    raise SystemExit('story deed still carries inline requirements: %s' % ', '.join(stray))

out = ['<?xml version="1.0" encoding="utf-8"?>', '<GameEffects xmlns="GameEffects">',
       '\t<!-- MODERN boost rewards at 40 percent. GENERATED by tools/gen-eni-mo-boosts.py from',
       '\t     mo-deeds-gameeffects.xml - every boost carries the SAME inline requirements as its marker',
       '\t     twin, so the two can never drift. Edit the deeds file, then re-run the generator. -->']
for key, (node, system) in NODES.items():
    out.append('\t<Modifier id="ENI_MO_BOOST_%s" collection="COLLECTION_OWNER" effect="EFFECT_PLAYER_GRANT_PROGRESSION" permanent="true" run-once="true">' % key)
    if key in reqs:
        out.append('\t\t' + reqs[key].strip())
    out.append('\t\t<Argument name="Amount">1</Argument>')
    out.append('\t\t<Argument name="BoostPercentage">40</Argument>')
    out.append('\t\t<Argument name="SystemType">%s</Argument>' % system)
    out.append('\t\t<Argument name="FreeProgressionType">FREE_PROGRESSION_BOOST_SPECIFIC</Argument>')
    out.append('\t\t<Argument name="NodeType">%s</Argument>' % node)
    out.append('\t</Modifier>')
out.append('</GameEffects>')

open(os.path.join(ROOT, 'mo-boosts-40.xml'), 'w', encoding='utf-8').write("\n".join(out) + "\n")
print('wrote mo-boosts-40.xml: %d boosts mirrored from their markers' % len(NODES))

for pct in (10, 20, 30):
    rows = ['<?xml version="1.0" encoding="utf-8"?>',
            '<!-- Eureka & Inspiration: MODERN boost size %d percent override (GENERATED by' % pct,
            '     tools/gen-eni-mo-boosts.py - do not edit). Loads on top of the always-loaded 40',
            '     percent base when the setup selector is %d. -->' % pct,
            '<Database>', '\t<ModifierArguments>']
    for key in NODES:
        rows.append('\t\t<Update><Where ModifierId="ENI_MO_BOOST_%s" Name="BoostPercentage"/>'
                    '<Set Value="%d"/></Update>' % (key, pct))
    rows += ['\t</ModifierArguments>', '</Database>']
    open(os.path.join(ROOT, 'mo-boosts-set-%d.xml' % pct), 'w', encoding='utf-8').write("\n".join(rows) + "\n")
    print('wrote mo-boosts-set-%d.xml' % pct)

# The bind file: a Modifier is inert until instantiated. One row per attach wrapper.
bind = ['<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Eureka & Inspiration: MODERN deed binds (GENERATED by tools/gen-eni-mo-boosts.py -',
        '     do not edit). Without these rows the wrappers in mo-deeds-gameeffects.xml never',
        '     instantiate and every Modern deed is dead code with no error anywhere. -->',
        '<Database>', '\t<GameModifiers>']
for key in NODES:
    if key in STORY:
        continue          # story rewards do the attaching; there is no wrapper to bind
    bind.append('\t\t<Row ModifierId="ENI_MO_ATTACH_%s"/>' % key)
# Step-tracker wrappers too. THIS FILE IS GENERATED, so rows added by hand are silently wiped on
# the next run - which is exactly what happened on 2026-08-06 when Modern's trackers were built and
# the boosts regenerated straight afterwards. check-eni-drift.py caught it. Sweeping the deeds file
# means a newly added tracker binds automatically and can never be lost this way again.
steps = sorted(set(re.findall(r'<Modifier id="(ENI_MO_ATTACH_STEPS\d+)"',
                              open(os.path.join(ROOT, 'mo-deeds-gameeffects.xml'),
                                   encoding='utf-8').read())),
               key=lambda x: int(x.replace('ENI_MO_ATTACH_STEPS', '')))
for w in steps:
    bind.append('\t\t<Row ModifierId="%s"/>' % w)
bind += ['\t</GameModifiers>', '</Database>']
open(os.path.join(ROOT, 'mo-deeds-bind.xml'), 'w', encoding='utf-8').write("\n".join(bind) + "\n")
print('wrote mo-deeds-bind.xml: %d attach rows (%d story-delivered, no wrapper) + %d tracker wrapper(s)'
      % (len(NODES) - len(STORY), len(STORY), len(steps)))
