"""Generate docs/DEED-LIST.md - every boost in the mod, straight out of the shipped text files.

WHY GENERATED: this list feeds the README and the Steam Workshop description. Hand-maintaining it
guarantees it drifts the first time a deed is re-priced, and a Workshop description that lies about
its own contents is worse than no description. Re-run after any deed change; publish-eni.ps1 runs it
automatically so an export can never ship a stale list.

Node names come from ui/eni-core.js (ENI_NODE_LABELS) and the deed wording from text/*-text.xml, so
what a player reads here is what they read in-game, character for character.

Run:  python tools/gen-eni-deed-list.py
"""
import io, os, re, sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MOD = os.path.join(ROOT, 'mods', 'eureka-inspiration')
OUT = os.path.join(MOD, 'docs', 'DEED-LIST.md')

AGES = [('AQ', 'Antiquity', 'aq-text.xml'),
        ('EX', 'Exploration', 'ex-text.xml'),
        ('MO', 'Modern', 'mo-text.xml')]

# display names, so the list reads like the tech tree rather than like the data
core = open(os.path.join(MOD, 'ui', 'eni-core.js'), encoding='utf-8').read()
labels = dict(re.findall(r"(NODE_[A-Z_0-9]+):\s*'([^']+)'", core))


def label_for(age, key):
    """the tree's display name for a deed key, falling back to a de-slugged key"""
    for node, name in labels.items():
        if not node.startswith('NODE_'):
            continue
        tail = node.split('_')[-1] if '_MAIN_' not in node and '_BRANCH_' not in node else \
            node.split('_MAIN_')[-1].split('_BRANCH_')[-1]
        if ('_' + age + '_') in node and (node.endswith('_' + key) or tail == key):
            return name
    return key.replace('_', ' ').title()


rows = {}
for age, _, fname in AGES:
    src = open(os.path.join(MOD, 'text', fname), encoding='utf-8').read()
    found = []
    for key, desc in re.findall(
            r'<Row Tag="LOC_ENI_' + age + r'_([A-Z_0-9]+)_DESC"><Text>(.*?)</Text></Row>', src, re.S):
        if key.endswith('_UNIQUE') or key.endswith('_FISHING'):
            continue          # second markers on an existing deed, not a deed of their own
        found.append((label_for(age, key), desc.replace('&amp;', '&').replace('&apos;', "'").strip()))
    rows[age] = sorted(found)

total = sum(len(v) for v in rows.values())
out = ['# Eureka & Inspiration - every boost',
       '',
       '<!-- GENERATED by tools/gen-eni-deed-list.py - do not edit by hand. -->',
       '',
       'Every base-game Technology and Civic that can take a boost has one deed attached. Complete the',
       'deed and a **Eureka!** or **Inspiration** fires, pre-paying a share of that node\'s research -',
       '10%, 20%, 30% or 40%, chosen at game setup.',
       '',
       '**%d boosts across the three Ages.**' % total,
       '']
for age, name, _ in AGES:
    out += ['## %s - %d boosts' % (name, len(rows[age])), '',
            '| Node | Deed |', '|---|---|']
    out += ['| **%s** | %s |' % (n, d) for n, d in rows[age]]
    out.append('')

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
print('wrote %s' % os.path.relpath(OUT, ROOT))
for age, name, _ in AGES:
    print('   %-12s %d boosts' % (name, len(rows[age])))
print('   %-12s %d total' % ('', total))
