"""Regenerate data/aq-boosts-40.xml (and the 10/20/30 overrides) from aq-deeds-gameeffects.xml.

Antiquity's boost file used to be hand-maintained, which meant editing a MARKER did not update its
BOOST: the UI would track one condition while the boost paid on another. That happened for real
while re-cutting Currency (2026-08-02) and was caught only by an ad-hoc check. This mirrors the
Exploration generator, so the two can no longer disagree.

Every ENI_BOOST_* copies the SubjectRequirements of its ENI_MARK_* twin verbatim. The four
story-driven deeds (Wheel, Mysticism, Discipline, Tactics) carry NO inline requirements on either
side - their marker and boost are attached as narrative-story rewards, and the story's own
RequirementSet decides when they fire - so they are emitted without a requirement block, exactly as
before. Edit the deeds file only, then run this.
"""
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'mods', 'eureka-inspiration', 'data')

NODES = {
    'WRITING': ('NODE_TECH_AQ_WRITING', 'SYSTEM_TECH'),
    'IRRIGATION': ('NODE_TECH_AQ_IRRIGATION', 'SYSTEM_TECH'),
    'MASONRY': ('NODE_TECH_AQ_MASONRY', 'SYSTEM_TECH'),
    'CURRENCY': ('NODE_TECH_AQ_CURRENCY', 'SYSTEM_TECH'),
    'BRONZE_WORKING': ('NODE_TECH_AQ_BRONZE_WORKING', 'SYSTEM_TECH'),
    'MILITARY_TRAINING': ('NODE_TECH_AQ_MILITARY_TRAINING', 'SYSTEM_TECH'),
    'IRON_WORKING': ('NODE_TECH_AQ_IRON_WORKING', 'SYSTEM_TECH'),
    'PUBLIC_LIFE': ('NODE_CIVIC_AQ_MAIN_PUBLIC_LIFE', 'SYSTEM_CULTURE'),
    'CODE_OF_LAWS': ('NODE_CIVIC_AQ_MAIN_CODE_OF_LAWS', 'SYSTEM_CULTURE'),
    'ENTERTAINMENT': ('NODE_CIVIC_AQ_MAIN_ENTERTAINMENT', 'SYSTEM_CULTURE'),
    'CITIZENSHIP': ('NODE_CIVIC_AQ_MAIN_CITIZENSHIP', 'SYSTEM_CULTURE'),
    'ORG_MILITARY': ('NODE_CIVIC_AQ_MAIN_ORG_MILITARY', 'SYSTEM_CULTURE'),
    'LITERACY': ('NODE_CIVIC_AQ_MAIN_LITERACY', 'SYSTEM_CULTURE'),
    'SKILLED_TRADES': ('NODE_CIVIC_AQ_MAIN_SKILLED_TRADES', 'SYSTEM_CULTURE'),
    'PHILOSOPHY': ('NODE_CIVIC_AQ_MAIN_PHILOSOPHY', 'SYSTEM_CULTURE'),
    'COMMERCE': ('NODE_CIVIC_AQ_MAIN_COMMERCE', 'SYSTEM_CULTURE'),
    'NAVIGATION': ('NODE_TECH_AQ_NAVIGATION', 'SYSTEM_TECH'),
    'ENGINEERING': ('NODE_TECH_AQ_ENGINEERING', 'SYSTEM_TECH'),
    'MATHEMATICS': ('NODE_TECH_AQ_MATHEMATICS', 'SYSTEM_TECH'),
    'WHEEL': ('NODE_TECH_AQ_WHEEL', 'SYSTEM_TECH'),
    'MYSTICISM': ('NODE_CIVIC_AQ_MAIN_MYSTICISM', 'SYSTEM_CULTURE'),
    'DISCIPLINE': ('NODE_CIVIC_AQ_MAIN_DISCIPLINE', 'SYSTEM_CULTURE'),
    'TACTICS': ('NODE_CIVIC_AQ_MAIN_TACTICS', 'SYSTEM_CULTURE'),
}

# story-delivered: no inline requirements on either marker or boost
STORY = {'WHEEL', 'MYSTICISM', 'DISCIPLINE', 'TACTICS'}

src = open(os.path.join(ROOT, 'aq-deeds-gameeffects.xml'), encoding='utf-8').read()
reqs = dict(re.findall(
    r'<Modifier id="ENI_MARK_([A-Z_]+)"[^>]*>\s*(<SubjectRequirements[^>]*>.*?</SubjectRequirements>)',
    src, re.S))

missing = [k for k in NODES if k not in reqs and k not in STORY]
if missing:
    raise SystemExit('no requirements found for: %s' % ', '.join(missing))

out = ['<?xml version="1.0" encoding="utf-8"?>', '<GameEffects xmlns="GameEffects">',
       '\t<!-- ANTIQUITY boost rewards at 40 percent. GENERATED by tools/gen-eni-aq-boosts.py from',
       '\t     aq-deeds-gameeffects.xml - every boost carries the SAME inline requirements as its marker',
       '\t     twin, so the two can never drift. The four story-driven deeds (Wheel, Mysticism,',
       '\t     Discipline, Tactics) carry none: their story RequirementSet decides when they fire.',
       '\t     Edit the deeds file, then re-run the generator. -->']
for key, (node, system) in NODES.items():
    out.append('\t<Modifier id="ENI_BOOST_%s" collection="COLLECTION_OWNER" effect="EFFECT_PLAYER_GRANT_PROGRESSION" permanent="true" run-once="true">' % key)
    if key not in STORY:
        out.append('\t\t' + reqs[key].strip())
    out.append('\t\t<Argument name="Amount">1</Argument>')
    out.append('\t\t<Argument name="BoostPercentage">40</Argument>')
    out.append('\t\t<Argument name="SystemType">%s</Argument>' % system)
    out.append('\t\t<Argument name="FreeProgressionType">FREE_PROGRESSION_BOOST_SPECIFIC</Argument>')
    out.append('\t\t<Argument name="NodeType">%s</Argument>' % node)
    out.append('\t</Modifier>')
out.append('</GameEffects>')

open(os.path.join(ROOT, 'aq-boosts-40.xml'), 'w', encoding='utf-8').write("\n".join(out) + "\n")
print('wrote aq-boosts-40.xml: %d boosts (%d mirrored, %d story-driven)'
      % (len(NODES), len(NODES) - len(STORY), len(STORY)))

# the setup screen's Boost Size selector loads one of these on top of the 40 percent base
for pct in (10, 20, 30):
    rows = ['<?xml version="1.0" encoding="utf-8"?>',
            '<!-- Eureka & Inspiration: ANTIQUITY boost size %d percent override (GENERATED by' % pct,
            '     tools/gen-eni-aq-boosts.py - do not edit). Loads on top of the always-loaded 40',
            '     percent base when the setup selector is %d. -->' % pct,
            '<Database>', '\t<ModifierArguments>']
    for key in NODES:
        rows.append('\t\t<Update><Where ModifierId="ENI_BOOST_%s" Name="BoostPercentage"/>'
                    '<Set Value="%d"/></Update>' % (key, pct))
    rows += ['\t</ModifierArguments>', '</Database>']
    open(os.path.join(ROOT, 'aq-boosts-set-%d.xml' % pct), 'w', encoding='utf-8').write("\n".join(rows) + "\n")
    print('wrote aq-boosts-set-%d.xml' % pct)
