"""Regenerate data/ex-boosts-40.xml from data/ex-deeds-gameeffects.xml.

Every ENI_EX_BOOST_* copies the SubjectRequirements of its ENI_EX_MARK_* twin verbatim, so a
deed's requirement can never drift between the marker (which drives the UI) and the boost
(which pays the research). Edit the deeds file only, then run this.
"""
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'mods', 'eureka-inspiration', 'data')

NODES = {
    'FEUDALISM': ('NODE_TECH_EX_FEUDALISM', 'SYSTEM_TECH'),
    'GUILDS': ('NODE_TECH_EX_GUILDS', 'SYSTEM_TECH'),
    'CASTLES': ('NODE_TECH_EX_CASTLES', 'SYSTEM_TECH'),
    'HERALDRY': ('NODE_TECH_EX_HERALDRY', 'SYSTEM_TECH'),
    'EDUCATION': ('NODE_TECH_EX_EDUCATION', 'SYSTEM_TECH'),
    'METALLURGY': ('NODE_TECH_EX_METALLURGY', 'SYSTEM_TECH'),
    'METALLURGY_UNIQUE': ('NODE_TECH_EX_METALLURGY', 'SYSTEM_TECH'),
    'SHIPBUILDING': ('NODE_TECH_EX_SHIPBUILDING', 'SYSTEM_TECH'),
    'ARCHITECTURE': ('NODE_TECH_EX_ARCHITECTURE', 'SYSTEM_TECH'),
    'METAL_CASTING': ('NODE_TECH_EX_METAL_CASTING', 'SYSTEM_TECH'),
    'GUNPOWDER': ('NODE_TECH_EX_GUNPOWDER', 'SYSTEM_TECH'),
    'URBAN_PLANNING': ('NODE_TECH_EX_URBAN_PLANNING', 'SYSTEM_TECH'),
    'REFORMATION': ('NODE_CIVIC_EX_BRANCH_REFORMATION', 'SYSTEM_CULTURE'),
    'AUTHORITY': ('NODE_CIVIC_EX_MAIN_AUTHORITY', 'SYSTEM_CULTURE'),
    'INSPIRATION': ('NODE_CIVIC_EX_MAIN_INSPIRATION', 'SYSTEM_CULTURE'),
    'MERCANTILISM': ('NODE_CIVIC_EX_MAIN_MERCANTILISM', 'SYSTEM_CULTURE'),
    'BUREAUCRACY': ('NODE_CIVIC_EX_MAIN_BUREAUCRACY', 'SYSTEM_CULTURE'),
    'COLONIALISM': ('NODE_CIVIC_EX_MAIN_COLONIALISM', 'SYSTEM_CULTURE'),
    'DIPLOMATIC_SERVICE': ('NODE_CIVIC_EX_MAIN_DIPLOMATIC_SERVICE', 'SYSTEM_CULTURE'),
    'SOCIETY': ('NODE_CIVIC_EX_MAIN_SOCIETY', 'SYSTEM_CULTURE'),
    'IMPERIALISM': ('NODE_CIVIC_EX_MAIN_IMPERIALISM', 'SYSTEM_CULTURE'),
    'SOCIAL_CLASS': ('NODE_CIVIC_EX_MAIN_SOCIAL_CLASS', 'SYSTEM_CULTURE'),
    'SOVEREIGNTY': ('NODE_CIVIC_EX_MAIN_SOVEREIGNTY', 'SYSTEM_CULTURE'),
}

src = open(os.path.join(ROOT, 'ex-deeds-gameeffects.xml'), encoding='utf-8').read()
reqs = dict(re.findall(
    r'<Modifier id="ENI_EX_MARK_([A-Z_]+)"[^>]*>\s*(<SubjectRequirements[^>]*>.*?</SubjectRequirements>)',
    src, re.S))

missing = [k for k in NODES if k not in reqs]
if missing:
    raise SystemExit('no requirements found for: %s' % ', '.join(missing))

out = ['<?xml version="1.0" encoding="utf-8"?>', '<GameEffects xmlns="GameEffects">',
       '\t<!-- EXPLORATION boost rewards at 40 percent. GENERATED by tools/gen-eni-ex-boosts.py from',
       '\t     ex-deeds-gameeffects.xml - every boost carries the SAME inline requirements as its marker',
       '\t     twin, so the two can never drift. Edit the deeds file, then re-run the generator. -->']
for key, (node, system) in NODES.items():
    out.append('\t<Modifier id="ENI_EX_BOOST_%s" collection="COLLECTION_OWNER" effect="EFFECT_PLAYER_GRANT_PROGRESSION" permanent="true" run-once="true">' % key)
    out.append('\t\t' + reqs[key].strip())
    out.append('\t\t<Argument name="Amount">1</Argument>')
    out.append('\t\t<Argument name="BoostPercentage">40</Argument>')
    out.append('\t\t<Argument name="SystemType">%s</Argument>' % system)
    out.append('\t\t<Argument name="FreeProgressionType">FREE_PROGRESSION_BOOST_SPECIFIC</Argument>')
    out.append('\t\t<Argument name="NodeType">%s</Argument>' % node)
    out.append('\t</Modifier>')
out.append('</GameEffects>')

open(os.path.join(ROOT, 'ex-boosts-40.xml'), 'w', encoding='utf-8').write("\n".join(out) + "\n")
print('wrote ex-boosts-40.xml: %d boosts mirrored from their markers' % len(NODES))

# The setup screen's Boost Size selector loads one of these on top of the always-loaded 40 percent
# base. Antiquity shipped its own set from the start; Exploration did not, so 10/20/30 silently paid
# 40 there until 2026-08-02. Generated from the same NODES map so a new deed cannot be missed.
for pct in (10, 20, 30):
    rows = ['<?xml version="1.0" encoding="utf-8"?>',
            '<!-- Eureka & Inspiration: EXPLORATION boost size %d percent override (GENERATED by' % pct,
            '     tools/gen-eni-ex-boosts.py - do not edit). Loads on top of the always-loaded 40',
            '     percent base when the setup selector is %d. -->' % pct,
            '<Database>', '\t<ModifierArguments>']
    for key in NODES:
        rows.append('\t\t<Update><Where ModifierId="ENI_EX_BOOST_%s" Name="BoostPercentage"/>'
                    '<Set Value="%d"/></Update>' % (key, pct))
    rows += ['\t</ModifierArguments>', '</Database>']
    open(os.path.join(ROOT, 'ex-boosts-set-%d.xml' % pct), 'w', encoding='utf-8').write("\n".join(rows) + "\n")
    print('wrote ex-boosts-set-%d.xml' % pct)
